### ISSUE TITLE
coffeescript registration lost after esm import

### ISSUE THREAD

**Issue by dbushong** [groupon/nilo#11]
If you have an `object-graph` file that ultimately somewhere tries to `require()` a coffeescript file, it doesn't seem to work.

I'm guessing it's related to the esm importing magic; if you `console.log(require.extensions)` right before this line: https://github.com/groupon/nilo/blob/bab3bcf133c38539087771c526e6ab614cd3f788/lib/project.js#L192

you see coffee, but if you do the same at the top of one of the `object-graph.js` files, the `coffee` registration is gone.

I'm not sure the right way to fix this; setting `extensions: true` in the `cjs` options to `esm()` didn't trivially fix it - do we still need ESM?  Can we just tell people to use `NODE_OPTIONS=--experimental-modules` if they want `mjs` support?

**Comment by jkrems** [comment]
I assume that `import(absoluteFileURL)` would work with `--experimental-modules` and its presence should be fine in modern node w/o the flag as long as nothing tries to actually call it. In other words: I think getting rid of `esm` is fairly reasonable. Hopefully sometime in the next few month we'll get a "real" modules implementation in node without a flag 🤞.

**Comment by dbushong** [comment]
Hmm.  Is there *any* way, let alone a *good* way to feature-detect and branch ESM-supporting code?

**Comment by dbushong** [comment]
I guess I could put the import-loading function into a `.mjs` file of its own, and try/catch requiring it?

**Comment by jkrems** [comment]
Starting at node 10, `import('./x')` isn't a syntax error. So in theory you could put it into a separate file right now and then remove that indirection once node 8 goes out of support.
